blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request Repository
    url: https://github.com/anupama-pathirage/test-service/issues/new
    about: Please submit new features in the product management repository.