blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug
    url: https://github.com/wso2/product-integrator/issues/new
    about: Submit Bugs through the Product public repository.
  
  - name: ğŸš€ Existing Customer Issue
    url: https://github.com/wso2-enterprise/wso2-integration-internal/issues/new
    about: Submit customer issues through the customer internal repository.

  - name: ğŸš€ Feature Request
    url: https://github.com/wso2-enterprise/integration-product-management/issues/new
    about: Submit new features through the Product Management repository.

  - name: ğŸ›  Improvement
    url: https://github.com/wso2-enterprise/integration-product-management/issues/new
    about: Submit improvements through the Product Management repository.

  - name: â“ Questions / Discussions
    url: https://discord.com/invite/wso2
    about: Please use Discord for general questions.