blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/ballerina-platform/ballerina-lang/issues/new
    about: Submit new features through the Product Management repository.

  - name: ğŸ›  Improvement / Enhancement
    url: https://github.com/ballerina-platform/ballerina-library/issues/new
    about: Submit product or engineering improvements in the designated repository.

  - name: â“ Questions / Discussions
    url: https://github.com/ballerina-platform/ballerina-distribution/issues/new
    about: Please use discussions for general questions.